//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransaction
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryDate { get; set; }
        public string CardType { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
    }
}
